version: '3.8'

services:
  vote:
    image: dockersamples/examplevotingapp_vote:before
    ports:
      - 5000:80
    networks:
      - Frontend

  redis:
    image: redis:4.0.11-alpine
    networks:
      - Frontend

  worker:
    image: dockersamples/examplevotingapp_worker
    networks:
      - Frontend
      - Backend

  db:
    image: postgres:14.2-alpine
    volumes: 
      - postgres_data:/var/lib/postgresql/data
    environment:
      # POSTGRES_USER: test_user_psql
      # POSTGRES_PASSWORD: password
      # POSTGRES_DB : test_db1
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - Backend

  result:
    image: dockersamples/examplevotingapp_result:before
    ports:
      - 5001:80
    networks:
      - Backend

networks:
  Frontend:
  Backend:

volumes:
  postgres_data:
